FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

COPY config.py .
COPY manage.py .
COPY app ./app

EXPOSE 8000

CMD ["uvicorn", "app.controller.controller:app", "--host", "0.0.0.0", "--port", "8000"]
